### ISSUE TITLE
Can not reproduce and Results mismatch

### ISSUE THREAD

**Issue by Ryanai1120** [qdrant/vector-db-benchmark#55]
Hello,

Thanks for the great work on this benchmark. I have a couple of questions:

It seems that we update the engine versions frequently, but I don't see any corresponding updates on the front page graph. Are there plans to address this? If not, it could be misleading.

I've reviewed a [forked repo](https://github.com/myscale/vector-db-benchmark) of this project, and they presented entirely different conclusions without any code changes. Additionally, I've had trouble reproducing the results shown in your front page graph. Could this be due to not updating the results in accordance with code changes?

Thank you.

**Comment by KShivendu** [comment]
Hi @Ryanai1120, 

> I've had trouble reproducing the results shown in your front page graph. Could this be due to not updating the results in accordance with code changes?

I think it's because of version changes. I've re-run benchmarks across similar but different machines and can confirm that they are reproducible (excluding small random fluctuations because of uncontrollable environmental reasons). 

Regarding, https://myscale.github.io/benchmark, I'd say that
- Comparing cloud offerings is never a reliable way to run benchmarks. 
- Even if you exclude network latency and keep the client and server in the same network, you'll encounter huge differences across different cloud providers because cloud instances are often very different despite looking very similar on the surface. 

Feel free to run our benchmarks and report anything that you find hard to reproduce despite having the [environment mentioned in our benchmarks](https://qdrant.tech/benchmarks/#setup). We are more than happy to help with that :)
